// UniLink · dati di prodotto della web app v3: aree di studio e registro «Da decidere».
// Il registro descrive l'ARCHITETTURA COMPLETA di ogni proposta: pagine (rotte), file, dati salvati,
// funzioni del motore, ricavi (ipotesi delle demo), dipendenze, passi per attivarla, domande aperte.
// I moduli con «modulo» funzionano davvero nella demo (codice in js/da-decidere/…); gli altri sono concetti da costruire.
// Per promuovere una proposta a sezione decisa: seguire «attivare» e spostare la voce nel gruppo giusto di js/boot.js.

window.UL_AREE = [
  { slug: "economia", nome: "Economia", stato: "attiva", colore: "#cf7527", tinta: "#f6e4d1",
    atenei: [{ slug: "unifi", nome: "UniFi", stato: "attivo" }],
    corsi: ["Economia Aziendale", "Economia e Commercio"],
    test: { nome: "TOLC-E", nota: "Test CISIA per i corsi di Economia: verifica sul bando del tuo ateneo se e come è richiesto.", fonte: "https://www.cisiaonline.it" } },
  { slug: "giurisprudenza", nome: "Giurisprudenza", stato: "in_arrivo", colore: "#2f4a8a", tinta: "#dfe4f1", decidere: "D01",
    atenei: [{ slug: "unifi", nome: "UniFi", stato: "in_arrivo" }],
    corsi: ["Giurisprudenza (ciclo unico)"], domanda: "A che anno sei?",
    test: null },
  { slug: "medicina", nome: "Medicina", stato: "in_arrivo", colore: "#1a453c", tinta: "#e3efe8", decidere: "D02",
    atenei: [{ slug: "unifi", nome: "UniFi", stato: "in_arrivo" }],
    corsi: ["Medicina e Chirurgia"], domanda: "Sei nel semestre filtro?",
    test: { nome: "Semestre filtro", nota: "Fisica, Chimica, Biologia: uguale in tutta Italia. Date e regole solo da fonti ufficiali.", fonte: "https://www.mur.gov.it" } },
  { slug: "altra", nome: "Un'altra area", stato: "proposta", colore: "#646b7b", tinta: "#eceef3",
    atenei: [], corsi: [], domanda: "Cosa studi?", test: null },
];

const CAREER = "js/da-decidere/career/", NET = "js/da-decidere/network/";
window.UL_DA_DECIDERE = [
  /* ===================== AREE ===================== */
  { id: "D01", gruppo: "Nuove aree", titolo: "Area Giurisprudenza", origine: "Nota Cosimo 6/10 · landing cap. 10", stato: "In arrivo", impatto: 5, sforzo: 4,
    cosa: "Oggi chi sceglie Giurisprudenza vede lo stato «in arrivo» con lista d'attesa (funziona già). Quando parte: stesse pagine di Studio, con materiali e corsi di Giurisprudenza.",
    modulo: { rotte: [["dashboard", "Dashboard in stato «in arrivo» (account Elena)"]], vista: "UL.U.arrivo() in js/views/unilink.js", persona: "arrivo" },
    file: ["js/unilink-dati.js → UL_AREE (riga giurisprudenza)", "js/views/unilink.js → arrivo(), bindArrivo()", "js/data-dispense.js (materiali con area)"],
    dati: ["profile.area = \"giurisprudenza\"", "activity.waitlist.giurisprudenza = risposta alla domanda"],
    funzioni: ["UL.U.attiva(user) decide se mostrare le pagine o lo stato «in arrivo»"],
    ricavi: "Come Economia (pacchetti esame/semestre, Plus).",
    dipendenze: ["1–2 studenti di Giurisprudenza nel team", "Piano di studi verificato sul Course Catalogue UniFi"],
    attivare: ["UL_AREE: stato da «in_arrivo» ad «attiva»", "Aggiungere i corsi in data-dispense.js con il campo area", "Domande d'esame in data-quiz.js per gli esami pilota"],
    domande: ["Parte prima Giurisprudenza o Medicina? (decide la lista d'attesa)", "Quali 3 esami per primi?"],
    storico: [["2026-10-06", "v3: stato «in arrivo» con lista d'attesa nella app."]] },
  { id: "D02", gruppo: "Nuove aree", titolo: "Area Medicina", origine: "Nota Cosimo 6/10 · landing cap. 1 e 10", stato: "In arrivo", impatto: 5, sforzo: 5,
    cosa: "Come D01. Particolarità: il semestre filtro (Fisica, Chimica, Biologia) è nazionale: si può riusare il modulo «Test e simulazioni» (D16) con una banca dedicata.",
    modulo: null, file: ["js/unilink-dati.js → UL_AREE (riga medicina)", "D16 per il semestre filtro"], dati: ["profile.area = \"medicina\"", "activity.waitlist.medicina"],
    funzioni: ["UL.U.attiva(user)"], ricavi: "Pacchetti per il semestre filtro (ipotesi).", dipendenze: ["Studenti di Medicina", "Fonti ufficiali MUR per date e programma"],
    attivare: ["Come D01", "Banca domande per Fisica, Chimica, Biologia nel formato di D16"], domande: ["Semestre filtro o esami del triennio?", "Ciclo realistico: 2027/28?"],
    storico: [["2026-10-06", "v3: stato «in arrivo» (account Noemi solo per le metriche)."]] },

  /* ===================== CAREER (dalla demo C) ===================== */
  { id: "D03", gruppo: "Career (demo C)", titolo: "Il mio piano · Career Score", origine: "Demo Versione C · HQ CURRICULUM", stato: "Da valutare",
    cosa: "Punteggio di carriera su 100 in 5 aree (accademico, lingue, esperienze, network, preparazione), 5 fasi (Esami → Esperienze → Stage → Magistrale → Lavoro) e le prossime 3 azioni.",
    modulo: { rotte: [["piano", "Il mio piano"]], vista: "UL.views.pianoC in " + CAREER + "viste-percorso.js", persona: "plus" },
    file: [CAREER + "core.js → C.score, C.phases, C.nextActions, C.talentPct", CAREER + "viste-percorso.js → pianoC", "js/store.js → career(profile) per media e CFU"],
    dati: ["profile: media/CFU (o libretto), inglese, certInglese, gmat/gre, stage, erasmus, extracurricolari, areeProf", "activity: talent.visible, rsvp, tracks, bookings, applications, shortlist"],
    funzioni: ["C.score(u) → {total, parts[5]}", "C.phases(u) → 5 fasi con checklist e stato done/now/next", "C.nextActions(u) → prime 3 azioni non fatte"],
    ricavi: "Indiretto: porta a Track, mentor e Plus (ipotesi demo C).", dipendenze: ["Profilo completo (Informazioni personali)", "Pesi del punteggio da validare con il team"],
    attivare: ["Aggiungere { k: \"piano\", l: \"Il mio piano\" } al gruppo «Dopo gli esami» in js/boot.js", "Rivedere i pesi in C.score e le soglie in C.phases", "Spiegare il punteggio allo studente (non è una promessa)"],
    domande: ["Un punteggio numerico è utile o mette ansia?", "Chi decide i pesi?"],
    storico: [["2026-10-06", "v3: modulo completo della demo C, funzionante nella app."]] },
  { id: "D04", gruppo: "Career (demo C)", titolo: "Studio con Plus", origine: "Demo Versione C", stato: "Da valutare",
    cosa: "Variante di «Studio» pensata per Career: dispense gratuite, esercitazioni incluse in Plus.", modulo: { rotte: [["studio", "Studio"]], vista: "UL.views.studioC in " + CAREER + "viste-percorso.js", persona: "plus" },
    file: [CAREER + "viste-percorso.js → studioC"], dati: ["activity.favorites, downloads"], funzioni: ["C.isPlus(u)"],
    ricavi: "Plus (demo C: €39/semestre).", dipendenze: ["Decisione sul gratuito (D10)"],
    attivare: ["Non serve se resta il modello B (pacchetti): è un'alternativa da confrontare"], domande: ["Dispense gratis + Plus, o pacchetti a pagamento?"],
    storico: [["2026-10-06", "v3: modulo della demo C."]] },
  { id: "D05", gruppo: "Career (demo C)", titolo: "Opportunità: stage e graduate program", origine: "Demo Versione C", stato: "Da valutare",
    cosa: "Annunci di stage, graduate program e case competition delle aziende partner, con candidatura rapida e tracker dello stato.",
    modulo: { rotte: [["opportunita", "Opportunità"]], vista: "UL.views.opportunitaC", persona: "plus" },
    file: [CAREER + "dati.js → companies, jobs (esempi fittizi)", CAREER + "viste-percorso.js → opportunitaC"],
    dati: ["activity.applications: {id, job, st: inviata|colloquio|offerta|chiusa, at}"], funzioni: ["C.co(id) azienda", "notifiche scadenze in boot (jobs con dl ≤ 20)"],
    ricavi: "Aziende: annuncio €290, partner annuale €4.900 (ipotesi demo C).", dipendenze: ["Aziende partner vere (oggi nessuna)", "Soggetto legale e contratti"],
    attivare: ["Sostituire gli annunci di esempio con una collezione vera (Supabase)", "Voce «Opportunità» nel gruppo «Dopo gli esami»"], domande: ["Ha senso prima di avere partner?"],
    storico: [["2026-10-06", "v3: modulo della demo C (aziende fittizie)."]] },
  { id: "D06", gruppo: "Career (demo C)", titolo: "Profilo talento", origine: "Demo Versione C", stato: "Da valutare",
    cosa: "Profilo per le aziende (headline, competenze, LinkedIn), visibile solo con consenso, con badge e CV.",
    modulo: { rotte: [["profilo", "Profilo talento"]], vista: "UL.views.profiloC", persona: "plus" },
    file: [CAREER + "viste-percorso.js → profiloC", CAREER + "core.js → talentPct"], dati: ["profile.headline, skills[], linkedin", "activity.talent.visible (consenso)"],
    funzioni: ["C.talentPct(u) completezza %"], ricavi: "Business school: contatti con consenso €40 (ipotesi demo C).", dipendenze: ["Privacy: consenso esplicito e revocabile"],
    attivare: ["Informativa privacy dedicata", "Voce nel gruppo Account"], domande: ["Chi vede il profilo?"], storico: [["2026-10-06", "v3: modulo della demo C."]] },
  { id: "D07", gruppo: "Career (demo C)", titolo: "Track (percorsi guidati)", origine: "Demo Versione C", stato: "Da valutare",
    cosa: "Percorsi a moduli (MSc, Finance & Consulting, Erasmus) con avanzamento, a numero chiuso.",
    modulo: { rotte: [["track", "Track"]], vista: "UL.views.trackC in " + CAREER + "viste-crescita.js", persona: "plus" },
    file: [CAREER + "dati.js → tracks", CAREER + "viste-crescita.js → trackC"], dati: ["activity.tracks: {id, at, done[indici moduli]}"], funzioni: ["C.track(id)"],
    ricavi: "Track €49–349 (ipotesi demo C).", dipendenze: ["Contenuti e tutor per ogni track"], attivare: ["Scrivere i moduli veri", "Voce nel gruppo «Dopo gli esami»"],
    domande: ["Quale track per primo?"], storico: [["2026-10-06", "v3: modulo della demo C."]] },
  { id: "D08", gruppo: "Career (demo C)", titolo: "Mentor marketplace", origine: "Demo Versione C · B (mentor)", stato: "Da valutare",
    cosa: "Mentor 1:1 (studenti e laureati) con prenotazione dello slot e pagamento. Nella parte decisa c'è già la versione semplice (Il mio percorso → Mentor).",
    modulo: { rotte: [["mentor", "Mentor"]], vista: "UL.views.mentorC", persona: "plus" },
    file: [CAREER + "dati.js → mentors", CAREER + "viste-crescita.js → mentorC"], dati: ["activity.bookings: {id, mentor, when, price, topic}"], funzioni: ["C.mentor(id)"],
    ricavi: "Commissione 25% sulle sessioni (ipotesi demo C).", dipendenze: ["Mentor veri, pagamenti, fatturazione"], attivare: ["Unificare con il mentor di «Il mio percorso»"],
    domande: ["Gratis tra studenti o a pagamento?"], storico: [["2026-10-06", "v3: modulo della demo C."]] },
  { id: "D09", gruppo: "Career (demo C)", titolo: "Eventi", origine: "Demo Versione C", stato: "Da valutare",
    cosa: "Info session, workshop ed eventi con iscrizione.", modulo: { rotte: [["eventi", "Eventi"]], vista: "UL.views.eventiC", persona: "plus" },
    file: [CAREER + "dati.js → events", CAREER + "viste-percorso.js → eventiC"], dati: ["activity.rsvp: id eventi"], funzioni: [],
    ricavi: "Business school: info session €1.500 (ipotesi demo C).", dipendenze: ["Calendario eventi vero"], attivare: ["Collezione eventi in Supabase"], domande: ["Unire con Club ed eventi (D19)?"],
    storico: [["2026-10-06", "v3: modulo della demo C."]] },
  { id: "D10", gruppo: "Career (demo C)", titolo: "Plus e inviti (referral)", origine: "Demo Versione C · HQ Referral", stato: "Da valutare",
    cosa: "Pagina Plus con piani e codice invito personale (crediti per chi invita). Il Plus della parte decisa usa già lo stesso campo activity.plus.",
    modulo: { rotte: [["plus", "Plus e inviti"]], vista: "UL.views.plusC", persona: "plus" },
    file: [CAREER + "viste-percorso.js → plusC", CAREER + "core.js → isPlus"], dati: ["activity.plus {active, plan, since}", "activity.referral {code, invited, credits}"], funzioni: ["C.isPlus(u) (usato anche da B.plus)"],
    ricavi: "Plus €39/semestre nella demo C; in «Piano e acquisti» ipotesi 4,99 €/mese.", dipendenze: ["Listino (HQ)", "Stripe"], attivare: ["Scegliere un solo prezzo Plus", "Aggiungere il codice invito a «Piano e acquisti»"],
    domande: ["Plus mensile, a semestre o annuale?", "Referral: crediti o sconto?"], storico: [["2026-10-06", "v3: modulo della demo C."]] },
  { id: "D11", gruppo: "Career (demo C)", titolo: "Business cockpit (admin)", origine: "Demo Versione C", stato: "Da valutare",
    cosa: "Per il team: ricavi per fonte, pipeline aziende, listino B2B, modello a 3 anni con ipotesi modificabili.",
    modulo: { rotte: [["cockpit", "Business cockpit"]], vista: "UL.views.adminC", persona: "admin" },
    file: [CAREER + "viste-crescita.js → adminC", CAREER + "core.js → pipeline, savePipeline"], dati: ["localStorage ul_varC_b2b (pipeline)"], funzioni: ["C.pipeline()"],
    ricavi: "—", dipendenze: ["Solo ruolo admin"], attivare: ["Spostare in HQ invece che nella app?"], domande: ["Vive nella app o nell'HQ?"], storico: [["2026-10-06", "v3: modulo della demo C."]] },

  /* ===================== NETWORK (dalla demo D) ===================== */
  { id: "D12", gruppo: "Network (demo D)", titolo: "Più atenei: home dell'ateneo", origine: "Demo Versione D", stato: "Da valutare",
    cosa: "Ogni studente sceglie il proprio ateneo: home con colori, club, dispense ed eventi dell'ateneo, e la rete degli altri atenei.",
    modulo: { rotte: [["home", "Home dell'ateneo"]], vista: "UL.views.homeD in " + NET + "home-vista.js", persona: "network" },
    file: [NET + "dati.js → unis, chapters", NET + "core.js → uni, myUni", NET + "home-vista.js → homeD"], dati: ["profile.ateneo, corso", "activity.chapter"], funzioni: ["D.myUni(u)", "D.ST stati ateneo"],
    ricavi: "Sponsor e convenzioni locali (ipotesi demo D).", dipendenze: ["Persone negli altri atenei", "Nome e dominio (oggi «UniLink Firenze»)"],
    attivare: ["Campo ateneo in UL_AREE (atenei) già previsto", "Voce «Home» al posto della Dashboard per chi non è UniFi"], domande: ["Quando uscire da Firenze?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D13", gruppo: "Network (demo D)", titolo: "Dispense dalla community (+ crediti)", origine: "Demo Versione D · HQ Raccolta domande", stato: "Da valutare",
    cosa: "Gli studenti caricano dispense del loro corso; il club le revisiona; chi carica riceve crediti.",
    modulo: { rotte: [["dispense", "Dispense per ateneo"]], vista: "UL.views.dispenseD", persona: "network" },
    file: [NET + "dati.js → community", NET + "core.js → dispense(uniId), addCredits", NET + "dispense-vista.js"], dati: ["activity.uploads: {uni, cds, anno, title, pages, status: pending|approved|rejected}", "activity.credits"],
    funzioni: ["D.dispense(uni)", "D.addCredits(u, n, perché)"], ricavi: "Indiretto (contenuti gratuiti), crediti spendibili.", dipendenze: ["Revisione dei contenuti", "Diritti d'autore sugli appunti"],
    attivare: ["Flusso di revisione nell'HQ", "Regole sui crediti"], domande: ["Crediti, sconto o commissione (HQ)?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D14", gruppo: "Network (demo D)", titolo: "Calcolatori e guide per ateneo", origine: "Demo Versione D", stato: "Da valutare",
    cosa: "Voto di laurea con le regole di ogni ateneo, punteggio exchange, guide su agevolazioni e residenze.",
    modulo: { rotte: [["strumenti", "Calcolatori e guide"]], vista: "UL.views.strumentiD in " + NET + "community-vista.js", persona: "network" },
    file: [NET + "core.js → PRESETS, laurea(), exchange(), DESTINATIONS"], dati: ["nessuno (calcoli)"], funzioni: ["D.laurea(x)", "D.exchange(x)"], ricavi: "—",
    dipendenze: ["Regole ufficiali di ogni ateneo (i preset sono esempi)"], attivare: ["Verificare i preset con i regolamenti"], domande: ["Sostituisce i tool del sito?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D15", gruppo: "Network (demo D)", titolo: "Mercatino dei libri", origine: "Demo Versione D", stato: "Da valutare",
    cosa: "Annunci di libri usati del proprio corso, con annunci in evidenza a pagamento.", modulo: { rotte: [["mercatino", "Mercatino"]], vista: "UL.views.mercatinoD", persona: "network" },
    file: [NET + "dati.js → listings", NET + "community-vista.js → mercatinoD"], dati: ["activity.listings"], funzioni: [], ricavi: "Annunci in evidenza (ipotesi demo D).",
    dipendenze: ["Moderazione"], attivare: ["Collezione annunci in Supabase"], domande: ["Serve o basta WhatsApp?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D16", gruppo: "Network (demo D)", titolo: "Test d'ingresso e simulazioni", origine: "Demo Versione D · HQ TOLC", stato: "Nuova (HQ)", impatto: 5, sforzo: 5,
    cosa: "Diagnostico gratuito, allenamento per materia, simulazioni a tempo (TOLC, test magistrali), predittore di ammissione, tutoring 1:1.",
    modulo: { rotte: [["test", "Test e simulazioni"]], vista: "UL.views.testD in " + NET + "prep-vista.js", persona: "network" },
    file: [NET + "dati.js → subjects, apt (domande), tests, tutoring", NET + "core.js → stat, answer, subjects, best, predict", NET + "prep-vista.js → testD"],
    dati: ["activity.tests {sessions[], stats{qid: seen, ok, last}}", "activity.purchases (selfstudy, tutoring)"], funzioni: ["D.subjects(u)", "D.best(u, test)", "D.predict(media, score, prog)"],
    ricavi: "Self-study €49, tutoring €149–499 (ipotesi demo D).", dipendenze: ["Banca domande vera", "Settore competitivo (commento Cosimo)"],
    attivare: ["Banca domande TOLC-E", "Voce nel gruppo Studio o percorso dedicato"], domande: ["Ha senso prima delle nuove aree?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D17", gruppo: "Network (demo D)", titolo: "Ammissioni MSc", origine: "Demo Versione D", stato: "Da valutare",
    cosa: "Chi è entrato in quale master, con media e test: dati segnalati dagli studenti.", modulo: { rotte: [["ammissioni", "Ammissioni MSc"]], vista: "UL.views.ammissioniD", persona: "network" },
    file: [NET + "dati.js → admissions", NET + "prep-vista.js → ammissioniD"], dati: ["activity.admissions (segnalazioni)"], funzioni: ["D.predict()"], ricavi: "—",
    dipendenze: ["Dati veri e verificati (regola HQ: niente statistiche inventate)"], attivare: ["Raccolta segnalazioni con consenso"], domande: ["Quanti dati servono per essere utili?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D18", gruppo: "Network (demo D)", titolo: "Academy (corsi on-demand)", origine: "Demo Versione D", stato: "Da valutare",
    cosa: "Corsi brevi (Excel, investimenti, modelli finanziari) con avanzamento.", modulo: { rotte: [["academy", "Academy"]], vista: "UL.views.academyD", persona: "network" },
    file: [NET + "dati.js → academy", NET + "prep-vista.js → academyD"], dati: ["activity.courses {id, done}", "activity.purchases (academy)"], funzioni: ["D.buy(u, item)"],
    ricavi: "Corsi €29–89 (ipotesi demo D).", dipendenze: ["Chi produce i corsi"], attivare: ["Primo corso vero"], domande: ["È il nostro mestiere?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D19", gruppo: "Network (demo D)", titolo: "Club ed eventi per ateneo", origine: "Demo Versione D · HQ Ambassador", stato: "Da valutare",
    cosa: "Un club UniLink per ateneo con ambassador, eventi locali e nazionali, convenzioni.", modulo: { rotte: [["club", "Club ed eventi"]], vista: "UL.views.clubD", persona: "network" },
    file: [NET + "dati.js → chapters, events, deals", NET + "community-vista.js → clubD"], dati: ["activity.chapter, rsvp, ambassador"], funzioni: [], ricavi: "Sponsor degli eventi, convenzioni (ipotesi demo D).",
    dipendenze: ["Ambassador veri"], attivare: ["Programma ambassador (HQ)"], domande: ["Unire con Eventi (D09)?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D20", gruppo: "Network (demo D)", titolo: "Pass e crediti", origine: "Demo Versione D", stato: "Da valutare",
    cosa: "Abbonamento Pass e crediti guadagnati caricando dispense, spendibili nella app.", modulo: { rotte: [["pass", "Pass e crediti"]], vista: "UL.views.passD in " + NET + "home-vista.js", persona: "network" },
    file: [NET + "core.js → isPass, addCredits"], dati: ["activity.pass {active, since}", "activity.credits"], funzioni: ["D.isPass(u)", "D.hasPrep(u)"], ricavi: "Pass €5,99/mese (ipotesi demo D).",
    dipendenze: ["Un solo abbonamento: Pass (D) o Plus (C)?"], attivare: ["Scegliere tra Pass e Plus"], domande: ["Crediti come valuta interna: sì o no?"], storico: [["2026-10-06", "v3: modulo della demo D."]] },
  { id: "D21", gruppo: "Network (demo D)", titolo: "La rete (admin)", origine: "Demo Versione D", stato: "Da valutare",
    cosa: "Per il team: revisione delle dispense caricate, dati per ateneo, ricavi, candidature ambassador.", modulo: { rotte: [["rete", "La rete"]], vista: "UL.views.adminD", persona: "admin" },
    file: [NET + "admin-vista.js → adminD"], dati: ["tutti gli utenti (UL.store.allUsers)"], funzioni: [], ricavi: "—", dipendenze: ["Solo ruolo admin"], attivare: ["Spostare la revisione nell'HQ?"], domande: ["App o HQ?"],
    storico: [["2026-10-06", "v3: modulo della demo D."]] },

  /* ===================== IDEE HQ SENZA MODULO (da costruire) ===================== */
  { id: "D22", gruppo: "Idee HQ da costruire", titolo: "Raccolta domande d'esame", origine: "HQ · Raccolta domande esami (in sviluppo)", stato: "In sviluppo (HQ)", impatto: 5, sforzo: 3,
    cosa: "Form «Com'è andato l'esame?» il giorno dopo l'appello; revisione del team; le domande entrano nelle Esercitazioni.", modulo: null,
    file: ["da creare: js/da-decidere/domande/vista.js", "riuso: js/data-quiz.js (formato domande)", "riuso: D13 (flusso di revisione)"],
    dati: ["activity.segnalazioni: {slug, data, testo, stato}"], funzioni: ["da creare: invio, revisione, pubblicazione in UL_QUIZ"], ricavi: "Indiretto.",
    dipendenze: ["Regola di ricompensa (HQ: crediti, sconto, commissione)"], attivare: ["Chiedere la costruzione del modulo (tipo A)"], domande: ["Anonimo di default?"], storico: [["2026-10-06", "Concetto: modulo da costruire."]] },
  { id: "D23", gruppo: "Idee HQ da costruire", titolo: "Lettore protetto delle dispense", origine: "HQ · Visualizzazione material in sito", stato: "Nuova (HQ)", impatto: 3, sforzo: 3,
    cosa: "Lettore nella app con PDF.js e filigrana con nome ed email; il PDF non si scarica.", modulo: null,
    file: ["da creare: js/lettore.js (PDF.js)", "server: funzione di filigrana (pdf-lib)"], dati: ["activity.read (pagine lette)"], funzioni: ["da creare"], ricavi: "Protegge i pacchetti a pagamento.",
    dipendenze: ["Archivio privato Supabase"], attivare: ["Chiedere la costruzione del modulo"], domande: ["Download consentito a chi ha pagato?"], storico: [["2026-10-06", "Concetto: modulo da costruire."]] },
  { id: "D24", gruppo: "Idee HQ da costruire", titolo: "Borse di studio", origine: "HQ · BORSE DI STUDIO", stato: "Nuova (HQ)", impatto: 4, sforzo: 4,
    cosa: "Guida con informazioni chiave e scadenze del bando DSU, sempre con link alla fonte.", modulo: null,
    file: ["da creare: scheda in «Il mio percorso»"], dati: ["nessuno"], funzioni: [], ricavi: "—", dipendenze: ["Fonti ufficiali aggiornate"], attivare: ["Chiedere la costruzione"], domande: ["Statica o aggiornata in automatico?"],
    storico: [["2026-10-06", "Concetto: modulo da costruire."]] },
  { id: "D25", gruppo: "Idee HQ da costruire", titolo: "Guida tesi", origine: "HQ · NEW Tool - TESI", stato: "Nuova (HQ)", impatto: 4, sforzo: 3,
    cosa: "Percorso in 4 passi (argomento, relatore, scrittura, consegna) e template impaginato.", modulo: null,
    file: ["da creare: scheda in «Il mio percorso»"], dati: ["activity.tesi"], funzioni: [], ricavi: "—", dipendenze: ["Template", "Regole di consegna"], attivare: ["Chiedere la costruzione"], domande: ["Solo Economia?"],
    storico: [["2026-10-06", "Concetto: modulo da costruire."]] },
];
